### ISSUE TITLE
Fail on use of undeclared metadata

### ISSUE THREAD

**Issue by sbrookes** [draperlaboratory/hope-policy-tool#20]
@JohnPMerrill  and I just found this: 

The policy-tool should error if I forget to declare a tag `T` in the `Metadata:` section of my DPL, but set it in my initialization routines and use it in rules. Currently it happily builds and tag `T` never shows up anywhere.

**Comment by ccasin** [comment]
@sbrookes @JohnPMerrill 

I just tried to repro this (looking for good tasks for Amanda) and it doesn't seem to still be a problem?  Can you confirm it seems to be fixed now, or clarify the issue.

**Comment by JohnPMerrill** [comment]
My attempt to repro this (removing the Doctor tag from the ppac policy) gives me an appropriate policy-tool error:
```
Unable to find symbol Doctor in modules: osv.userType, osv.ppac, osv.password, osv.testComplex, osv.testS
imple, osv.none, osv.threeClass, osv.heap, osv.taint, osv.stack, osv.rwx, osv.riscv, osv.cfi, osv.frtos.m
ain reached from: osv.ppac
```

**Comment by ccasin** [comment]
OK, I'm going to assume I fixed it at some point and forgot to close the issue.  Closing now.  Thanks!
